### PR TITLE
Automatically generate news from php.net atom feed

### PR DESCRIPTION
**Pull request by connerbw**
I noticed that the http://windows.php.net/ homepage feels out of date (Last update: 20 Mar 2015, under that: PHP 5.5.0 Release Announcement :ouch: ) That doesn't inspire a lot of confidence IMHO. For an outsider it looks like a dead project.

This PR generates the news using `http://php.net/feed.atom` from items categorized as releases.

Sorry for the sloppy commits and multi-edits. If you approved this PR, please use GitHub's "Squash & Merge" feature to clean it up.

## Howto

 + Run: `php  script\generate_news_page.php`
 + Look at, maybe manually edit, the resulting `docroot\news.php` file.
 + Commit changes to GitHub.
 + Sync windows.php.net

Best regards,

### CODE REVIEW

**Comment by weltling** [comment]
Thanks for taking care of this. It might be a good idea to generate news as a cronjob or as a git hook, anyway. Yet some points

- the generated content should not be checked in
- not sure the old items should be removed, maybe kind of archived
- there still should be a possibility to put some specific items not necessarily from the feed, those should be indeed checked in and integrated into the generation process

Maybe there's more, lets see what you say :)

Thanks.

**Comment by connerbw** [comment]
Thanks for the reply @weltling 

> the generated content should not be checked in

Ok, good idea.

The current content  [is checked in](https://github.com/php/web-windows/blob/master/docroot/index.php#L34). There is also a history commits where people are manually editing HTML.  I was trying to follow what I thought was the convention and keep it minimal.

What resources does windows.php.net have? Can I create a sqlite file using Pdo? Some other database? A text file in a temp directory? A seperate HTML file in .gitignore? Please advise.

> not sure the old items should be removed, maybe kind of archived

>there still should be a possibility to put some specific items not necessarily from the feed, those should be indeed checked in and integrated into the generation process

Ok. Sounds good. But, same questions as before. If you can provide me with some guidelines as to how you want this done, i'll try again.

Regards,

**Comment by connerbw** [comment]
There's also the theoretical possibility that `http://php.net/feed.atom` gets temporarily hijacked, has `<?php //code ?>` in the content, where by automatically generating from that feed will compromise the website. 

My original intention was using this script as more of a helper to fish out and format news easily, but would also let a person double check it, maybe change, then commit it when they are happy. 

Auto-generation will need to sanitize a bit more.

**Comment by weltling** [comment]
@connerbw basically, i has been done this way till now, because there are no much news to share and having some complex kinda blog software were not justified. Your idea is quite simple, so IMO it fits well in this approach. Of course if we fetch NEWS from somewhere, it should be sanitized.

The host itself can get any resources required, but as you see from the code - there are none that would be required. Some content gets generated or read from JSON files. In this case probably it could be kept simple as well. Basically, the news file could be generated on demand. Fe like here https://github.com/php/web-windows/blob/master/include/listing.php#L89 . Or doing it per a cronjob were probably even more suitable. Or even both. I know, that's an additional I/O, but still it's more reliable than having additional services we don't really need, etc. The less complexity, the better :) Otherwise OFC, you can touch any needed places in .gitignore or where ever else.

I'd suggest to go this way. Fe the permanent news would be checked in like in data/news, the the fetched news, the could be stored somewhere like in data/feeds or take a better name. When the time comes, a cronjob or the site itself fetches the RSS feed and composes it together with the news that are checked it. We'd probably need to workout a rule on how to do that, probably comparing dates with RSS vs. checked in were ok for the start. Once the news are composed, it's written into the file that can be included into the site. For the windows.php.net specific news we could take either some RSS suitable format, or just put them as HTML. The old news can be attached as is, or converted to the choosen format once and checked in. Fe that's how the php.net site handles the news entries https://github.com/php/web-php/tree/master/archive/entries .

Thanks.

**Comment by connerbw** [comment]
Ok. Great, I'll try to have an updated PR by the end of the week. (Sorry for the delay. Work / family / hobby time management)

**Comment by weltling** [comment]
@connerbw sounds good. That's not a super urgent matter, so time should be taken to do it a proper way :)

Thanks.

**Comment by connerbw** [comment]
This fell off my radar. I ran out of time, steam. TODO 😞 

I will open a new PR sometime in the future, hopefully.

**Pull request closed without merging**
