### PR TITLE
Offer PHP 7.4 snapshots

### PR DESCRIPTION
**Pull request by cmb69**

### CODE REVIEW

**Comment by weltling** [comment]
Thanks for the PR. There should be some more, please see https://github.com/php/web-windows/commit/979d55ed3f240a7fb2e026d51a3eb47cd5bedc83. Releases could be added later probably, but actually could get everything at once.

Thanks.

**Comment by cmb69** [comment]
Ah, thanks! This is why the AVX builds are actually listed as x64, although generate_snap_page.php lists them as x86. I'll try to follow up with some clean-up PR.

**Comment by weltling** [comment]
That's fine. We used to have AVX x86, but in the mean time we don't build them (same no x64 TS for AVX). Those orphan entries can be cleaned up of course.

Thanks.

**Comment by weltling** [comment]
This one looks ok so far, can you merge please?

Thanks.

**Comment by cmb69** [comment]
Applied as eecd329732fa16f325689548b6b08ce2c108ae1c.

**Pull request closed without merging**
