### PR TITLE
HTML Cleanup

### PR DESCRIPTION
**Pull request by Sobak**
Since git-web sync finally works (thanks @weltling!) I proceeded to do quick HTML cleanup, mostly regarding to unused code and duplicated header/footer for the `index.php`.

Changes are in separate commits, I think these are rather non-controversial so I grouped them in single pull request. Let me know if you think otherwise, I will split them.

### CODE REVIEW

**Comment by weltling** [comment]
Great you come to it, @Sobak! I till now could care about the functional part and content. So yeah, please merge this PR and the other one.

Thanks.

**Comment by Sobak** [comment]
Hi Anatol,

thanks you appreciate that! I'd like to merge these changes but I don't have karma for `web-windows`. AFAIR this repo is a subject to Windows Team, not Wesite Team, when it comes to the `global_avail` file structure. I would need separate rule to merge PRs myself, as I'm surely not a part of Windows Team. I thought it will be simpler for you to merge pull requests to this repo.

**Comment by Sobak** [comment]
@weltling, I found it and can confirm

http://svn.php.net/viewvc/SVNROOT/global_avail?revision=342380&view=markup#l438

**Comment by weltling** [comment]
ACK, i'll merge these. You could request karma , if you'd wish, but otherwise it's fine this way, too. I'd be otherwise not coming to the design stuff in any foreseeable future, anyway :) Probably PRs are good anyway, as there are some services on those sites, that are coupled with the website, so the changes need some care to not to break it.

Much appreciated, thanks.

**Comment by weltling** [comment]
Merged, thanks!

**Pull request closed without merging**
