### PR TITLE
Matt is no longer part of the Windows team

### PR DESCRIPTION
**Pull request by cmb69**
Not sure about some others listed here.

### CODE REVIEW

**Comment by cmb69** [comment]
Maybe we should move alumni to a respective section instead of removing them.

**Comment by weltling** [comment]
@cmb69 what exactly is your suggestion with alumni?

Thanks.

**Comment by cmb69** [comment]
I mean *former* members of the team could be listed in a separte section at the end.

**Comment by weltling** [comment]
@cmb69 missed this one. If not removing, but keeping the list somewhere, probably it should be good.

Thanks.

**Comment by cmb69** [comment]
@weltling, I've noticed that I had inadvertently removed Venkat Raman Don, so I've restructured a bit, and styled with a flexbox. It's easier to make changes now, and looks better as well:
screenshot

**Comment by cmb69** [comment]
Applied as 372bda23828017d80767bc31393022b774e629d8. Thanks!

**Pull request closed without merging**
